### 스키마 정의 ###

In [1]:
import re
import pandas as pd
from collections import Counter

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\yeseo\AppData\Local\Temp\ipykernel_45444\158129675.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\yeseo\AppData\Local\Temp\ipykernel_45444\158129675.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\yeseo\AppData\Local\Temp\ipykernel_45444\158129675.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\yeseo\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\yeseo\AppData\Local\Temp\ipykernel_45444\158129675.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\yeseo\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

In [2]:
with open("../data/raw/error.log", encoding='utf-8', errors='replace') as f:
    lines = [l.rstrip("\n") for l in f if l.strip()]

print(f"총 라인 수: {len(lines)}")

총 라인 수: 629

#### 1. 전체 라인 preview ####

In [3]:
for line in lines[:20]:
    print(line)

[Thu Jun 12 13:35:25.818494 2025] [suexec:notice] [pid 1947900:tid 140420159084864] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
[Thu Jun 12 13:35:25.840609 2025] [lbmethod_heartbeat:notice] [pid 1947900:tid 140420159084864] AH02282: No slotmem from mod_heartmonitor
[Thu Jun 12 13:35:25.841319 2025] [http2:warn] [pid 1947900:tid 140420159084864] AH02951: mod_ssl does not seem to be enabled
[Thu Jun 12 13:35:25.843764 2025] [mpm_event:notice] [pid 1947900:tid 140420159084864] AH00489: Apache/2.4.37 (Rocky Linux) configured -- resuming normal operations
[Thu Jun 12 13:35:25.843784 2025] [core:notice] [pid 1947900:tid 140420159084864] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Jun 12 13:35:37.052218 2025] [autoindex:error] [pid 1947909:tid 140419562436352] [client 210.110.68.35:59629] AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
[Thu Jun 12 16:43:50.991473 2025] [autoindex:error] [pid 1947909:tid 140419308443392] [client 210.110.68.35:56126] AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
[Thu Jun 12 16:56:59.210399 2025] [autoindex:error] [pid 1947909:tid 140418427635456] [client 210.110.64.41:32198] AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
[Thu Jun 12 16:58:25.662484 2025] [autoindex:error] [pid 1948138:tid 140419182618368] [client 220.67.241.146:55672] AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
[Thu Jun 12 16:59:32.899367 2025] [autoindex:error] [pid 1948138:tid 140419149047552] [client 210.110.64.41:12775] AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
[Thu Jun 12 17:17:47.172289 2025] [autoindex:error] [pid 1947909:tid 140419283265280] [client 220.67.241.146:55981] AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
[Thu Jun 12 17:41:39.972769 2025] [mpm_event:notice] [pid 1947900:tid 140420159084864] AH00492: caught SIGWINCH, shutting down gracefully
[Thu Jun 12 17:42:00.043754 2025] [suexec:notice] [pid 1995107:tid 140658241005888] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
[Thu Jun 12 17:42:00.056234 2025] [lbmethod_heartbeat:notice] [pid 1995107:tid 140658241005888] AH02282: No slotmem from mod_heartmonitor
[Thu Jun 12 17:42:00.056705 2025] [http2:warn] [pid 1995107:tid 140658241005888] AH02951: mod_ssl does not seem to be enabled
[Thu Jun 12 17:42:00.058629 2025] [mpm_event:notice] [pid 1995107:tid 140658241005888] AH00489: Apache/2.4.37 (Rocky Linux) configured -- resuming normal operations
[Thu Jun 12 17:42:00.058647 2025] [core:notice] [pid 1995107:tid 140658241005888] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Jun 12 17:54:43.052352 2025] [mpm_event:notice] [pid 1995107:tid 140658241005888] AH00492: caught SIGWINCH, shutting down gracefully

#### 2. 라인 별 브래킷 [...] 개수 count -> 구조 유형 분류 ####

In [4]:
bracket_counts = Counter(line.count("[") for line in lines)
print("브래킷 개수 별 라인 수: ", bracket_counts)

for n in bracket_counts:
    print(f"\n---브래킷 {n}개인 라인 샘플 ---")
    samples = [l for l in lines if l.count("[") -- n][:3]
    for s in samples:
        print(s)

브래킷 개수 별 라인 수:  Counter({4: 459, 3: 152, 0: 18})

---브래킷 3개인 라인 샘플 ---
[Thu Jun 12 13:35:25.818494 2025] [suexec:notice] [pid 1947900:tid 140420159084864] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
[Thu Jun 12 13:35:25.840609 2025] [lbmethod_heartbeat:notice] [pid 1947900:tid 140420159084864] AH02282: No slotmem from mod_heartmonitor

---브래킷 0개인 라인 샘플 ---
[Thu Jun 12 13:35:25.818494 2025] [suexec:notice] [pid 1947900:tid 140420159084864] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Jun 12 13:35:25.840609 2025] [lbmethod_heartbeat:notice] [pid 1947900:tid 140420159084864] AH02282: No slotmem from mod_heartmonitor
[Thu Jun 12 13:35:25.841319 2025] [http2:warn] [pid 1947900:tid 140420159084864] AH02951: mod_ssl does not seem to be enabled

---브래킷 4개인 라인 샘플 ---
[Thu Jun 12 13:35:25.818494 2025] [suexec:notice] [pid 1947900:tid 140420159084864] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
[Thu Jun 12 13:35:25.840609 2025] [lbmethod_heartbeat:notice] [pid 1947900:tid 140420159084864] AH02282: No slotmem from mod_heartmonitor

#### 3. 라인 [,] 기준으로 쪼갠 후 각 조각 확인 ####

In [5]:
for line in lines[:10]:
    parts = re.findall(r'\[([^\]]*)\]', line)   # 브래킷 안 내용들만 추출
    remainder = re.sub(r'\[[^\]]*\]', '', line).strip()  # 브래킷 뺀 나머지
    print("brackets: ", parts)
    print("remainder: ", remainder)
    print("---")

brackets:  ['Thu Jun 12 13:35:25.818494 2025', 'suexec:notice', 'pid 1947900:tid 140420159084864']
remainder:  AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
---
brackets:  []
remainder:  AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive globally to suppress this message
---
brackets:  ['Thu Jun 12 13:35:25.840609 2025', 'lbmethod_heartbeat:notice', 'pid 1947900:tid 140420159084864']
remainder:  AH02282: No slotmem from mod_heartmonitor
---
brackets:  ['Thu Jun 12 13:35:25.841319 2025', 'http2:warn', 'pid 1947900:tid 140420159084864']
remainder:  AH02951: mod_ssl does not seem to be enabled
---
brackets:  ['Thu Jun 12 13:35:25.843764 2025', 'mpm_event:notice', 'pid 1947900:tid 140420159084864']
remainder:  AH00489: Apache/2.4.37 (Rocky Linux) configured -- resuming normal operations
---
brackets:  ['Thu Jun 12 13:35:25.843784 2025', 'core:notice', 'pid 1947900:tid 140420159084864']
remainder:  AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
---
brackets:  ['Thu Jun 12 13:35:37.052218 2025', 'autoindex:error', 'pid 1947909:tid 140419562436352', 'client 210.110.68.35:59629']
remainder:  AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
---
brackets:  ['Thu Jun 12 16:43:50.991473 2025', 'autoindex:error', 'pid 1947909:tid 140419308443392', 'client 210.110.68.35:56126']
remainder:  AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
---
brackets:  ['Thu Jun 12 16:56:59.210399 2025', 'autoindex:error', 'pid 1947909:tid 140418427635456', 'client 210.110.64.41:32198']
remainder:  AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
---
brackets:  ['Thu Jun 12 16:58:25.662484 2025', 'autoindex:error', 'pid 1948138:tid 140419182618368', 'client 220.67.241.146:55672']
remainder:  AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
---

#### 4. 브래킷 안 내용 중 콜론 유무 별로 구분 ####

In [6]:
first_bracket_contents = [re.findall(r'\[([^\]]*)\]', l) for l in lines]
for parts in first_bracket_contents[:15]:
    print(parts)

['Thu Jun 12 13:35:25.818494 2025', 'suexec:notice', 'pid 1947900:tid 140420159084864']
[]
['Thu Jun 12 13:35:25.840609 2025', 'lbmethod_heartbeat:notice', 'pid 1947900:tid 140420159084864']
['Thu Jun 12 13:35:25.841319 2025', 'http2:warn', 'pid 1947900:tid 140420159084864']
['Thu Jun 12 13:35:25.843764 2025', 'mpm_event:notice', 'pid 1947900:tid 140420159084864']
['Thu Jun 12 13:35:25.843784 2025', 'core:notice', 'pid 1947900:tid 140420159084864']
['Thu Jun 12 13:35:37.052218 2025', 'autoindex:error', 'pid 1947909:tid 140419562436352', 'client 210.110.68.35:59629']
['Thu Jun 12 16:43:50.991473 2025', 'autoindex:error', 'pid 1947909:tid 140419308443392', 'client 210.110.68.35:56126']
['Thu Jun 12 16:56:59.210399 2025', 'autoindex:error', 'pid 1947909:tid 140418427635456', 'client 210.110.64.41:32198']
['Thu Jun 12 16:58:25.662484 2025', 'autoindex:error', 'pid 1948138:tid 140419182618368', 'client 220.67.241.146:55672']
['Thu Jun 12 16:59:32.899367 2025', 'autoindex:error', 'pid 1948138:tid 140419149047552', 'client 210.110.64.41:12775']
['Thu Jun 12 17:17:47.172289 2025', 'autoindex:error', 'pid 1947909:tid 140419283265280', 'client 220.67.241.146:55981']
['Thu Jun 12 17:41:39.972769 2025', 'mpm_event:notice', 'pid 1947900:tid 140420159084864']
['Thu Jun 12 17:42:00.043754 2025', 'suexec:notice', 'pid 1995107:tid 140658241005888']
[]

#### 5. 메시지 앞 부분 'AH#####' 있는 라인/없는 라인 비율

In [7]:
has_code = sum(1 for l in lines if re.search(r'AH\d{5}', l))
print(f"AH##### 코드 포함 라인: {has_code}/{len(lines)}")

no_code_samples = [l for l in lines if not re.search(r'AH\d{5}', l)][:10]
for s in no_code_samples:
    print(s)

AH##### 코드 포함 라인: 629/629

In [8]:
SCHEMA_PATTERN = re.compile(
    r'^\[(?P<time_raw>[^\]]+)\] '
    r'\[(?P<module>[^:\]]+):(?P<level>[^\]]+)\] '
    r'\[pid (?P<pid>\d+)(?::tid (?P<tid>\d+))?\] '
    r'(?:\[client (?P<client_ip>[^:\]]+):(?P<client_port>\d+)\] )?'
    r'(?P<message>.*)$'
)

ERROR_CODE_PATTERN = re.compile(r'AH(?P<error_code>\d{5})')

In [9]:
records = []
for i, line in enumerate(lines):
    m = SCHEMA_PATTERN.match(line)
    ec = ERROR_CODE_PATTERN.search(line)

    record = {
        "line_no": i,
        "raw_no": line,
        "time_raw": None,
        "raw": line,
        ### --- error_log_고유 컬럼 --- ###
        "is_standard_format": m is not None,
        "module": None,
        "level": None,
        "pid": None,
        "tid": None,
        "client_ip": None,
        "client_port": None,
        "error_code": f"AH{ec.group('error_code')}" if ec else None,
        "message": None,
        "is_valid": None,
        "validation_errors": [],
    }

    if m:
        g = m.groupdict()
        record.update({
            "time_raw": g["time_raw"],
            "module": g["module"],
            "level": g["level"],
            "pid": g["pid"],
            "tid": g["tid"],
            "client_ip": g["client_ip"],
            "client_port": g["client_port"],
            "message": g["message"],
        })
    else:
        record["message"] = line

    records.append(record)

df = pd.DataFrame(records)
print(f"표준 포맷: {df['is_standard_format'].sum()}/{len(df)}")
df.head(10)

표준 포맷: 611/629

,line_no,raw_no,time_raw,raw,is_standard_format,module,level,pid,tid,client_ip,client_port,error_code,message,is_valid,validation_errors
0,0,[Thu Jun 12 13:35:25.818494 2025] [suexec:noti...,Thu Jun 12 13:35:25.818494 2025,[Thu Jun 12 13:35:25.818494 2025] [suexec:noti...,True,suexec,notice,1947900,140420159084864,None,None,AH01232,AH01232: suEXEC mechanism enabled (wrapper: /u...,None,[]
1,1,AH00558: httpd: Could not reliably determine t...,None,AH00558: httpd: Could not reliably determine t...,False,None,None,None,None,None,None,AH00558,AH00558: httpd: Could not reliably determine t...,None,[]
2,2,[Thu Jun 12 13:35:25.840609 2025] [lbmethod_he...,Thu Jun 12 13:35:25.840609 2025,[Thu Jun 12 13:35:25.840609 2025] [lbmethod_he...,True,lbmethod_heartbeat,notice,1947900,140420159084864,None,None,AH02282,AH02282: No slotmem from mod_heartmonitor,None,[]
3,3,[Thu Jun 12 13:35:25.841319 2025] [http2:warn]...,Thu Jun 12 13:35:25.841319 2025,[Thu Jun 12 13:35:25.841319 2025] [http2:warn]...,True,http2,warn,1947900,140420159084864,None,None,AH02951,AH02951: mod_ssl does not seem to be enabled,None,[]
4,4,[Thu Jun 12 13:35:25.843764 2025] [mpm_event:n...,Thu Jun 12 13:35:25.843764 2025,[Thu Jun 12 13:35:25.843764 2025] [mpm_event:n...,True,mpm_event,notice,1947900,140420159084864,None,None,AH00489,AH00489: Apache/2.4.37 (Rocky Linux) configure...,None,[]
5,5,[Thu Jun 12 13:35:25.843784 2025] [core:notice...,Thu Jun 12 13:35:25.843784 2025,[Thu Jun 12 13:35:25.843784 2025] [core:notice...,True,core,notice,1947900,140420159084864,None,None,AH00094,AH00094: Command line: '/usr/sbin/httpd -D FOR...,None,[]
6,6,[Thu Jun 12 13:35:37.052218 2025] [autoindex:e...,Thu Jun 12 13:35:37.052218 2025,[Thu Jun 12 13:35:37.052218 2025] [autoindex:e...,True,autoindex,error,1947909,140419562436352,210.110.68.35,59629,AH01276,AH01276: Cannot serve directory /home/dsuser/:...,None,[]
7,7,[Thu Jun 12 16:43:50.991473 2025] [autoindex:e...,Thu Jun 12 16:43:50.991473 2025,[Thu Jun 12 16:43:50.991473 2025] [autoindex:e...,True,autoindex,error,1947909,140419308443392,210.110.68.35,56126,AH01276,AH01276: Cannot serve directory /home/dsuser/:...,None,[]
8,8,[Thu Jun 12 16:56:59.210399 2025] [autoindex:e...,Thu Jun 12 16:56:59.210399 2025,[Thu Jun 12 16:56:59.210399 2025] [autoindex:e...,True,autoindex,error,1947909,140418427635456,210.110.64.41,32198,AH01276,AH01276: Cannot serve directory /home/dsuser/:...,None,[]
9,9,[Thu Jun 12 16:58:25.662484 2025] [autoindex:e...,Thu Jun 12 16:58:25.662484 2025,[Thu Jun 12 16:58:25.662484 2025] [autoindex:e...,True,autoindex,error,1948138,140419182618368,220.67.241.146,55672,AH01276,AH01276: Cannot serve directory /home/dsuser/:...,None,[]

In [10]:
from datetime import datetime

def parse_timestamp(time_raw: str):
    try:
        return datetime.strptime(time_raw, "%a %b %d %H:%M:%S.%f %Y")
    except ValueError:
        return None

def validate_row(row):
    errors = []

    if not row["is_standard_format"]:
        errors.append("format_mismatch")
        return None, errors

    ts = parse_timestamp(row["time_raw"]) if row["time_raw"] else None
    if ts is None:
        errors.append("timestamp_unparseable")

    if row["pid"] is None or not str(row["pid"]).isdigit():
        errors.append("pid_invalid")

    if row["level"] not in ["warn", "error", "notice"]:
        errors.append("level_unexpected")

    return ts, errors

In [11]:
results = df.apply(validate_row, axis=1, result_type="expand")
df["time"] = results[0]
df["validation_errors"] = results[1]
df["is_valid"] = df["validation_errors"].apply(len) == 0

print(f"실질 유효: {df['is_valid'].sum()}/{len(df)} ({df['is_valid'].mean()*100:.1f}%)")
df[~df["is_valid"]][["is_standard_format", "raw", "validation_errors"]].head(10)

실질 유효: 611/629 (97.1%)

,is_standard_format,raw,validation_errors
1,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]
14,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]
21,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]
28,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]
35,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]
42,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]
53,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]
66,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]
87,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]
104,False,AH00558: httpd: Could not reliably determine t...,[format_mismatch]

In [12]:
# 성공(형식 통과) / 실패(형식 불통과) 분리
df_success = df[df["is_standard_format"] == True].copy()
df_failure = df[df["is_standard_format"] == False].copy()

# validation_errors(list)는 CSV 저장을 위해 문자열로 변환
df_success["validation_errors"] = df_success["validation_errors"].apply(
    lambda x: ";".join(x) if isinstance(x, list) and len(x) > 0 else ""
)
df_failure["validation_errors"] = df_failure["validation_errors"].apply(
    lambda x: ";".join(x) if isinstance(x, list) and len(x) > 0 else ""
)

df_success.to_csv("error_parsed.csv", index=False, encoding="utf-8-sig")
df_failure.to_csv("error_parse_failure.csv", index=False, encoding="utf-8-sig")

print(f"error_parsed.csv: {len(df_success)}행")
print(f"error_parse_failure.csv: {len(df_failure)}행")

error_parsed.csv: 611행
error_parse_failure.csv: 18행

In [13]:
import pandas as pd

df_access_success = pd.read_csv("../data/interim/error_parsed.csv")
df_access_fail = pd.read_csv("../data/output/error_parse_failure.csv")

# 두 파일이 성공/실패로 나뉘어 있으므로 통계 내려면 합쳐야 함
df_access = pd.concat([df_access_success, df_access_fail], ignore_index=True)

print(df_access.columns.tolist())

['line_no', 'raw_no', 'time_raw', 'raw', 'is_standard_format', 'module', 'level', 'pid', 'tid', 'client_ip', 'client_port', 'error_code', 'message', 'is_valid', 'validation_errors', 'time']

In [17]:
import pandas as pd

# error_log 파싱 결과 불러오기 (실제 저장한 경로/파일명 그대로)
df_error_success = pd.read_csv("error_parsed.csv")
df_error_fail = pd.read_csv("error_parse_failure.csv")
df_error = pd.concat([df_error_success, df_error_fail], ignore_index=True)

# 타입 보정 (CSV에서 다시 읽으면 bool이 문자열로 깨질 수 있음)
for col in ["is_standard_format", "is_valid"]:
    if df_error[col].dtype == object:
        df_error[col] = df_error[col].astype(str).str.strip().str.lower() == "true"

def classify_parse_result(row):
    if not row["is_standard_format"]:
        return "FAILURE"
    elif not row["is_valid"]:
        return "PARTIAL"
    else:
        return "SUCCESS"

df_error["parse_result"] = df_error.apply(classify_parse_result, axis=1)

def classify_error_line(row):
    if not row["is_standard_format"]:
        return "헤더 없는 단독 메시지"
    elif pd.notna(row["client_ip"]):
        return "클라이언트 연관 이벤트"
    else:
        return "서버 자체 이벤트"

df_error["line_category"] = df_error.apply(classify_error_line, axis=1)

# ── 요약표 ──
summary = pd.DataFrame({
    "항목": [
        "전체 로그", "SUCCESS", "PARTIAL", "FAIL",
        "클라이언트 연관 이벤트", "서버 자체 이벤트", "헤더 없는 단독 메시지"
    ],
    "결과": [
        len(df_error),
        (df_error["parse_result"] == "SUCCESS").sum(),
        (df_error["parse_result"] == "PARTIAL").sum(),
        (df_error["parse_result"] == "FAILURE").sum(),
        (df_error["line_category"] == "클라이언트 연관 이벤트").sum(),
        (df_error["line_category"] == "서버 자체 이벤트").sum(),
        (df_error["line_category"] == "헤더 없는 단독 메시지").sum(),
    ]
})

print(summary.to_string(index=False))

print("\nlevel 분포:")
print(df_error["level"].value_counts())

print("\nmodule 분포:")
print(df_error["module"].value_counts())

          항목  결과
       전체 로그 629
     SUCCESS 611
     PARTIAL   0
        FAIL  18
클라이언트 연관 이벤트 449
   서버 자체 이벤트 162
헤더 없는 단독 메시지  18

level 분포:
level
warn      405
error     117
notice     89
Name: count, dtype: int64

module 분포:
module
proxy                 442
proxy_http             48
mpm_event              35
core                   26
http2                  18
lbmethod_heartbeat     18
suexec                 18
autoindex               6
Name: count, dtype: int64