In [1]:
from pathlib import Path
import re
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\yeseo\AppData\Local\Temp\ipykernel_10464\232305476.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\yeseo\AppData\Local\Temp\ipykernel_10464\232305476.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\yeseo\AppData\Local\Temp\ipykernel_10464\232305476.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\yeseo\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\yeseo\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\yeseo\AppData\Local\Temp\ipykernel_10464\232305476.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\yeseo\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\yeseo\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

In [31]:
## 0-1 / 경로 설정 ##
pd.set_option("display.max_colwidth", 150)

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
RAW_ERROR     = ROOT / "data" / "raw" / "error.log"
ERROR_PARSED  = ROOT / "data" / "interim" / "error_parsed.csv"
ERROR_FAIL    = ROOT / "data" / "output" / "error_parse_failure.csv"
OUT = ROOT / "reports" / "tables"
OUT.mkdir(parents=True, exist_ok=True)

for p in [RAW_ERROR, ERROR_PARSED, ERROR_FAIL]:
    print(p.exists(), p)

True C:\Users\yeseo\PycharmProjects\log-dlq-pipeline\data\raw\error.log
True C:\Users\yeseo\PycharmProjects\log-dlq-pipeline\data\interim\error_parsed.csv
True C:\Users\yeseo\PycharmProjects\log-dlq-pipeline\data\output\error_parse_failure.csv

In [32]:
## 0-2 / 데이터 로드 + 컬럼 확인 ##

df = pd.read_csv(ERROR_PARSED)
fail_csv = pd.read_csv(ERROR_FAIL)

with open(RAW_ERROR, encoding="utf-8", errors="replace") as f:
    lines = f.read().splitlines()

print("원본 행 수:", len(lines))          # 629 예상
print("error_parsed:", df.shape)
print("parse_failure:", fail_csv.shape)   # 18행 예상
print(df.columns.tolist())
df.head()

원본 행 수: 629
error_parsed: (611, 16)
parse_failure: (18, 16)
['line_no', 'raw_no', 'time_raw', 'raw', 'is_standard_format', 'module', 'level', 'pid', 'tid', 'client_ip', 'client_port', 'error_code', 'message', 'is_valid', 'validation_errors', 'time']

,line_no,raw_no,time_raw,raw,is_standard_format,module,level,pid,tid,client_ip,client_port,error_code,message,is_valid,validation_errors,time
0,0,[Thu Jun 12 13:35:25.818494 2025] [suexec:notice] [pid 1947900:tid 140420159084864] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec),Thu Jun 12 13:35:25.818494 2025,[Thu Jun 12 13:35:25.818494 2025] [suexec:notice] [pid 1947900:tid 140420159084864] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec),True,suexec,notice,1947900,140420159084864,NaN,NaN,AH01232,AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec),True,NaN,2025-06-12 13:35:25.818494
1,2,[Thu Jun 12 13:35:25.840609 2025] [lbmethod_heartbeat:notice] [pid 1947900:tid 140420159084864] AH02282: No slotmem from mod_heartmonitor,Thu Jun 12 13:35:25.840609 2025,[Thu Jun 12 13:35:25.840609 2025] [lbmethod_heartbeat:notice] [pid 1947900:tid 140420159084864] AH02282: No slotmem from mod_heartmonitor,True,lbmethod_heartbeat,notice,1947900,140420159084864,NaN,NaN,AH02282,AH02282: No slotmem from mod_heartmonitor,True,NaN,2025-06-12 13:35:25.840609
2,3,[Thu Jun 12 13:35:25.841319 2025] [http2:warn] [pid 1947900:tid 140420159084864] AH02951: mod_ssl does not seem to be enabled,Thu Jun 12 13:35:25.841319 2025,[Thu Jun 12 13:35:25.841319 2025] [http2:warn] [pid 1947900:tid 140420159084864] AH02951: mod_ssl does not seem to be enabled,True,http2,warn,1947900,140420159084864,NaN,NaN,AH02951,AH02951: mod_ssl does not seem to be enabled,True,NaN,2025-06-12 13:35:25.841319
3,4,[Thu Jun 12 13:35:25.843764 2025] [mpm_event:notice] [pid 1947900:tid 140420159084864] AH00489: Apache/2.4.37 (Rocky Linux) configured -- resuming...,Thu Jun 12 13:35:25.843764 2025,[Thu Jun 12 13:35:25.843764 2025] [mpm_event:notice] [pid 1947900:tid 140420159084864] AH00489: Apache/2.4.37 (Rocky Linux) configured -- resuming...,True,mpm_event,notice,1947900,140420159084864,NaN,NaN,AH00489,AH00489: Apache/2.4.37 (Rocky Linux) configured -- resuming normal operations,True,NaN,2025-06-12 13:35:25.843764
4,5,[Thu Jun 12 13:35:25.843784 2025] [core:notice] [pid 1947900:tid 140420159084864] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND',Thu Jun 12 13:35:25.843784 2025,[Thu Jun 12 13:35:25.843784 2025] [core:notice] [pid 1947900:tid 140420159084864] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND',True,core,notice,1947900,140420159084864,NaN,NaN,AH00094,AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND',True,NaN,2025-06-12 13:35:25.843784

In [5]:
# time → timestamp로 이름만 바꾸고, 나머지는 이름이 이미 맞음
df = df.rename(columns={"time": "timestamp"})

# timestamp 날짜 타입 변환: time 값 우선, 실패하면 time_raw(Apache 원문 형식)로 보완
t1 = pd.to_datetime(df["timestamp"], errors="coerce")
t2 = pd.to_datetime(df["time_raw"], format="%a %b %d %H:%M:%S.%f %Y", errors="coerce")
df["timestamp"] = t1.fillna(t2)

# is_standard_format이 CSV에서 문자열로 읽혔을 수도 있어서 bool로 통일
df["is_standard_format"] = df["is_standard_format"].astype(str).str.lower().eq("true")

# 분석 기준: 표준 헤더 형식인 행
ok = df[df["is_standard_format"]].copy()

print("전체:", len(df))                                  # 629 예상
print("표준 형식(분석 대상):", len(ok))                     # 611 예상
print("비표준 형식:", int((~df["is_standard_format"]).sum()))  # 18 예상
print("timestamp 변환 실패(표준 형식 중):", int(ok["timestamp"].isna().sum()))   # 0 예상

전체: 611
표준 형식(분석 대상): 611
비표준 형식: 0
timestamp 변환 실패(표준 형식 중): 0

In [9]:
## 원본에서 헤더 없는 행 찾기 ##
raw = pd.DataFrame({"line_no": range(1, len(lines) + 1), "raw": lines})
raw["module"] = raw["raw"].str.extract(r"^\[[^\]]+\]\s+\[([^:\]]*):")[0]
raw["has_header"] = raw["module"].notna()

no_ts = raw[~raw["has_header"]]
print("헤더 없는 행:", len(no_ts), "/ parse_failure.csv:", len(fail_csv))
display(no_ts["raw"].value_counts().to_frame("건수"))

헤더 없는 행: 18 / parse_failure.csv: 18

                                                                                                                                                        건수
raw
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using localhost.localdomain. Set the 'ServerName' directive ...  18

In [8]:
## 연속 줄 패턴 여부 ##
cont = no_ts["raw"].str.match(r"^(\s+|at\s|Traceback|Caused by)")
print("연속 줄 패턴:", int(cont.sum()), "/", len(no_ts))

연속 줄 패턴: 0 / 18

In [10]:
## 직전/직후 로그 비교 ##
rows = []
for ln in no_ts["line_no"]:
    prev = raw[raw["line_no"] == ln - 1]
    nxt  = raw[raw["line_no"] == ln + 1]
    next5 = raw[raw["line_no"].between(ln + 1, ln + 5)]["module"].dropna().tolist()
    rows.append({
        "line_no": ln,
        "prev_module": prev["module"].iloc[0] if len(prev) else None,
        "prev_raw": prev["raw"].iloc[0][:90] if len(prev) else None,
        "next_module": nxt["module"].iloc[0] if len(nxt) else None,
        "next_raw": nxt["raw"].iloc[0][:90] if len(nxt) else None,
        "next5_modules": ",".join(next5),
    })
neighbors = pd.DataFrame(rows)
display(neighbors)
print("직후 module 분포:"); display(neighbors["next_module"].value_counts(dropna=False))
print("직전 module 분포:"); display(neighbors["prev_module"].value_counts(dropna=False))

,line_no,prev_module,prev_raw,next_module,next_raw,next5_modules
0,2,suexec,[Thu Jun 12 13:35:25.818494 2025] [suexec:notice] [pid 1947900:tid 140420159084864] AH0123,lbmethod_heartbeat,[Thu Jun 12 13:35:25.840609 2025] [lbmethod_heartbeat:notice] [pid 1947900:tid 14042015908,"lbmethod_heartbeat,http2,mpm_event,core,autoindex"
1,15,suexec,[Thu Jun 12 17:42:00.043754 2025] [suexec:notice] [pid 1995107:tid 140658241005888] AH0123,lbmethod_heartbeat,[Thu Jun 12 17:42:00.056234 2025] [lbmethod_heartbeat:notice] [pid 1995107:tid 14065824100,"lbmethod_heartbeat,http2,mpm_event,core,mpm_event"
2,22,suexec,[Thu Jun 12 17:54:44.103613 2025] [suexec:notice] [pid 1995750:tid 140694063937856] AH0123,lbmethod_heartbeat,[Thu Jun 12 17:54:44.116054 2025] [lbmethod_heartbeat:notice] [pid 1995750:tid 14069406393,"lbmethod_heartbeat,http2,mpm_event,core,mpm_event"
3,29,suexec,[Thu Jun 12 17:56:07.326271 2025] [suexec:notice] [pid 1996011:tid 140669294074176] AH0123,lbmethod_heartbeat,[Thu Jun 12 17:56:07.339098 2025] [lbmethod_heartbeat:notice] [pid 1996011:tid 14066929407,"lbmethod_heartbeat,http2,mpm_event,core,mpm_event"
4,36,suexec,[Thu Jun 12 17:57:37.322539 2025] [suexec:notice] [pid 1996265:tid 139695085410624] AH0123,lbmethod_heartbeat,[Thu Jun 12 17:57:37.335006 2025] [lbmethod_heartbeat:notice] [pid 1996265:tid 13969508541,"lbmethod_heartbeat,http2,mpm_event,core,mpm_event"
5,43,suexec,[Thu Jun 12 17:58:37.904591 2025] [suexec:notice] [pid 1996504:tid 140592679917888] AH0123,lbmethod_heartbeat,[Thu Jun 12 17:58:37.917365 2025] [lbmethod_heartbeat:notice] [pid 1996504:tid 14059267991,"lbmethod_heartbeat,http2,mpm_event,core,proxy"
6,54,suexec,[Mon Jun 16 14:47:19.351148 2025] [suexec:notice] [pid 2065903:tid 140235550566720] AH0123,lbmethod_heartbeat,[Mon Jun 16 14:47:19.363946 2025] [lbmethod_heartbeat:notice] [pid 2065903:tid 14023555056,"lbmethod_heartbeat,http2,mpm_event,core,proxy"
7,67,suexec,[Mon Jun 16 15:33:18.474815 2025] [suexec:notice] [pid 971:tid 140566996662592] AH01232: s,lbmethod_heartbeat,[Mon Jun 16 15:33:18.501914 2025] [lbmethod_heartbeat:notice] [pid 971:tid 140566996662592,"lbmethod_heartbeat,http2,mpm_event,core,proxy"
8,88,suexec,[Mon Jun 16 15:47:24.759522 2025] [suexec:notice] [pid 8619:tid 139944384870720] AH01232:,lbmethod_heartbeat,[Mon Jun 16 15:47:24.775865 2025] [lbmethod_heartbeat:notice] [pid 8619:tid 13994438487072,"lbmethod_heartbeat,http2,mpm_event,core,proxy"
9,105,suexec,[Mon Jun 16 15:55:18.143070 2025] [suexec:notice] [pid 9255:tid 140660674214208] AH01232:,lbmethod_heartbeat,[Mon Jun 16 15:55:18.154954 2025] [lbmethod_heartbeat:notice] [pid 9255:tid 14066067421420,"lbmethod_heartbeat,http2,mpm_event,core,mpm_event"
10,112,suexec,[Mon Jun 16 15:55:45.999867 2025] [suexec:notice] [pid 1028:tid 140344454240576] AH01232:,lbmethod_heartbeat,[Mon Jun 16 15:55:46.024868 2025] [lbmethod_heartbeat:notice] [pid 1028:tid 14034445424057,"lbmethod_heartbeat,http2,mpm_event,core,proxy"
11,145,suexec,[Mon Jun 16 17:05:19.605355 2025] [suexec:notice] [pid 4612:tid 139657344936256] AH01232:,lbmethod_heartbeat,[Mon Jun 16 17:05:19.616909 2025] [lbmethod_heartbeat:notice] [pid 4612:tid 13965734493625,"lbmethod_heartbeat,http2,mpm_event,core,proxy"
12,156,suexec,[Mon Jun 16 17:07:27.115010 2025] [suexec:notice] [pid 1032:tid 139750706583872] AH01232:,lbmethod_heartbeat,[Mon Jun 16 17:07:27.143581 2025] [lbmethod_heartbeat:notice] [pid 1032:tid 13975070658387,"lbmethod_heartbeat,http2,mpm_event,core,proxy"
13,189,suexec,[Mon Jun 16 17:26:40.510383 2025] [suexec:notice] [pid 4208:tid 140120669116736] AH01232:,lbmethod_heartbeat,[Mon Jun 16 17:26:40.521952 2025] [lbmethod_heartbeat:notice] [pid 4208:tid 14012066911673,"lbmethod_heartbeat,http2,mpm_event,core,mpm_event"
14,196,suexec,[Mon Jun 16 17:27:03.869418 2025] [suexec:notice] [pid 4444:tid 140599448873280] AH01232:,lbmethod_heartbeat,[Mon Jun 16 17:27:03.881108 2025] [lbmethod_heartbeat:notice] [pid 4444:tid 14059944887328,"lbmethod_heartbeat,http2,mpm_event,core,proxy_http"
15,205,suexec,[Mon Jun 16 17:33:00.986365 2025] [suexec:notice] [pid 5118:tid 140485521467712] AH01232:,lbmethod_heartbeat,[Mon Jun 16 17:33:01.002334 2025] [lbmethod_heartbeat:notice] [pid 5118:tid 14048552146771,"lbmethod_heartbeat,http2,mpm_event,core,proxy"
16,265,suexec,[Sun Jul 06 10:23:00.093775 2025] [suexec:notice] [pid 1069:tid 140628547266880] AH01232:,lbmethod_heartbeat,[Sun Jul 06 10:23:00.204906 2025] [lbmethod_heartbeat:notice] [pid 1069:tid 14062854726688,"lbmethod_heartbeat,http2,mpm_event,core,proxy"
17,276,suexec,[Sun Jul 06 11:11:17.519358 2025] [suexec:notice] [pid 3959:tid 139858830911808] AH01232:,lbmethod_heartbeat,[Sun Jul 06 11:11:17.531548 2025] [lbmethod_heartbeat:notice] [pid 3959:tid 13985883091180,"lbmethod_heartbeat,http2,mpm_event,core,proxy"

직후 module 분포:

next_module
lbmethod_heartbeat    18
Name: count, dtype: int64

직전 module 분포:

prev_module
suexec    18
Name: count, dtype: int64

In [11]:
## 재시작 가설 확인 + 저장 ##
restart = ["suexec", "lbmethod_heartbeat", "http2", "mpm_event", "core"]
cnt = ok["module"].value_counts().reindex(restart).fillna(0).astype(int)
display(pd.DataFrame({"건수": cnt, "18과 동일": cnt == len(no_ts)}))

neighbors.to_csv(OUT / "error_missing_ts_neighbors.csv", index=False, encoding="utf-8-sig")

                    건수  18과 동일
module
suexec              18    True
lbmethod_heartbeat  18    True
http2               18    True
mpm_event           35   False
core                26   False

In [12]:
## Error timestamp 최소/최대/수집 기간 ##

ts = ok["timestamp"].dropna()
ts_summary = pd.DataFrame({"값": {
    "유효 timestamp 건수": len(ts),
    "최소": ts.min(),
    "최대": ts.max(),
    "수집 기간": ts.max() - ts.min(),
    "시간 역전 건수(파일 순서)": int((ts.diff() < pd.Timedelta(0)).sum()),
}})
display(ts_summary)
display(ts.dt.date.value_counts().sort_index().to_frame("일자별 건수"))
ts_summary.to_csv(OUT / "error_timestamp_range.csv", encoding="utf-8-sig")

                                          값
유효 timestamp 건수                         611
최소               2025-06-12 13:35:25.818494
최대               2025-07-27 22:36:24.119402
수집 기간               45 days 09:00:58.300908
시간 역전 건수(파일 순서)                           0

            일자별 건수
timestamp
2025-06-12      45
2025-06-16     149
2025-06-17       4
2025-06-18       3
2025-06-19       1
2025-06-20       2
2025-06-21       3
2025-06-22       8
2025-06-23       3
2025-06-25       2
2025-06-27       5
2025-06-28       4
2025-06-29       4
2025-06-30       6
2025-07-01       1
2025-07-02       2
2025-07-03       4
2025-07-06      20
2025-07-08       2
2025-07-09       7
2025-07-10      27
2025-07-11       5
2025-07-12      28
2025-07-13      55
2025-07-14      55
2025-07-15      29
2025-07-17       4
2025-07-18      31
2025-07-19      27
2025-07-20       1
2025-07-21      27
2025-07-22      29
2025-07-23       1
2025-07-24       2
2025-07-25       3
2025-07-27      12

In [13]:
## Level 분포 ##

level_dist = ok["level"].value_counts().to_frame("건수")
level_dist["비율(%)"] = (level_dist["건수"] / len(ok) * 100).round(1)
display(level_dist)

ALLOWED = {"emerg","alert","crit","error","warn","notice","info","debug"} | {f"trace{i}" for i in range(1, 9)}
bad_level = ~ok["level"].isin(ALLOWED)
print("허용값 외 level:", int(bad_level.sum()))
level_dist.to_csv(OUT / "error_level_dist.csv", encoding="utf-8-sig")

         건수  비율(%)
level
warn    405   66.3
error   117   19.1
notice   89   14.6

허용값 외 level: 0

In [14]:
## Module 분포 ##

module_dist = ok["module"].value_counts().to_frame("건수")
module_dist["비율(%)"] = (module_dist["건수"] / len(ok) * 100).round(1)
display(module_dist)
display(pd.crosstab(ok["module"], ok["level"], margins=True))
module_dist.to_csv(OUT / "error_module_dist.csv", encoding="utf-8-sig")

                     건수  비율(%)
module
proxy               442   72.3
proxy_http           48    7.9
mpm_event            35    5.7
core                 26    4.3
http2                18    2.9
lbmethod_heartbeat   18    2.9
suexec               18    2.9
autoindex             6    1.0

level               error  notice  warn  All
module
autoindex               6       0     0    6
core                    8      18     0   26
http2                   0       0    18   18
lbmethod_heartbeat      0      18     0   18
mpm_event               0      35     0   35
proxy                  55       0   387  442
proxy_http             48       0     0   48
suexec                  0      18     0   18
All                   117      89   405  611

In [15]:
## 코드 별 빈도 ##

code_freq = (ok.groupby(ok["error_code"].fillna("(코드 없음)"))
               .agg(건수=("level", "size"),
                    module=("module", lambda x: ",".join(sorted(x.dropna().unique()))),
                    level=("level",  lambda x: ",".join(sorted(x.dropna().unique()))),
                    예시=("message", "first"))
               .sort_values("건수", ascending=False))
code_freq["비율(%)"] = (code_freq["건수"] / len(ok) * 100).round(1)
print("고유 코드 수:", ok["error_code"].nunique())
display(code_freq)
code_freq.to_csv(OUT / "error_code_freq.csv", encoding="utf-8-sig")

고유 코드 수: 14

,건수,module,level,예시,비율(%)
error_code,,,,,
AH01092,387,proxy,warn,AH01092: no HTTP 0.9 request (with no host line) on incoming request and preserve host set forcing hostname to be dse.swu.ac.kr for uri /boaform/a...,63.3
AH00957,45,proxy,error,(111)Connection refused: AH00957: HTTP: attempt to connect to 210.110.104.16:5000 (210.110.104.16) failed,7.4
AH01114,45,proxy_http,error,"AH01114: HTTP: failed to make connection to backend: 210.110.104.16, referer: http://210.110.104.16/board",7.4
AH02282,18,lbmethod_heartbeat,notice,AH02282: No slotmem from mod_heartmonitor,2.9
AH00489,18,mpm_event,notice,AH00489: Apache/2.4.37 (Rocky Linux) configured -- resuming normal operations,2.9
AH00094,18,core,notice,AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND',2.9
AH02951,18,http2,warn,AH02951: mod_ssl does not seem to be enabled,2.9
AH01232,18,suexec,notice,AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec),2.9
AH00492,17,mpm_event,notice,"AH00492: caught SIGWINCH, shutting down gracefully",2.8
AH00126,8,core,error,AH00126: Invalid URI in request POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1,1.3
AH01095,7,proxy,error,(70008)Partial results are valid but processing is incomplete: [client 123.10.202.17:38746] AH01095: prefetch request body failed to 114.70.38.81:...,1.1
AH01276,6,autoindex,error,"AH01276: Cannot serve directory /home/dsuser/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Op...",1.0
AH00898,3,proxy,error,AH00898: Error reading from remote server returned by /,0.5
AH01102,3,proxy_http,error,(70007)The timeout specified has expired: [client 210.110.68.35:61825] AH01102: error reading status line from remote server 114.70.38.81:5000,0.5

In [16]:
## 코드-level 일관성 ##

lv = ok.dropna(subset=["error_code"]).groupby("error_code")["level"].nunique()
mixed_codes = lv[lv > 1].index.tolist()
print("level이 섞인 코드:", mixed_codes)
print("AH 코드 없는 행:", int(ok["error_code"].isna().sum()))

level이 섞인 코드: []
AH 코드 없는 행: 0

In [18]:
## Client IP 등장 빈도 ##

import ipaddress

def ip_type(ip):
    if pd.isna(ip): return None
    try: a = ipaddress.ip_address(str(ip))
    except ValueError: return "INVALID"
    return "LOOPBACK" if a.is_loopback else ("PRIVATE" if a.is_private else "PUBLIC")

ok["client_ip_type"] = ok["client_ip"].map(ip_type)
has_ip = ok["client_ip"].notna()
print(f"client 있음: {has_ip.sum()} / 없음(서버 이벤트): {(~has_ip).sum()}")   # 449 / 162 예상
print("고유 IP:", ok["client_ip"].nunique())
display(ok["client_ip_type"].value_counts(dropna=False).to_frame("건수"))

ip_freq = ok["client_ip"].value_counts().to_frame("건수")
ip_freq["비율(%)"] = (ip_freq["건수"] / has_ip.sum() * 100).round(1)
display(ip_freq.head(15))
ip_freq.to_csv(OUT / "error_client_ip_freq.csv", encoding="utf-8-sig")

client 있음: 449 / 없음(서버 이벤트): 162
고유 IP: 74

                 건수
client_ip_type
PUBLIC          449
None            162

                 건수  비율(%)
client_ip
47.83.14.24      52   11.6
121.186.31.54    52   11.6
210.110.68.35    39    8.7
169.211.232.182  26    5.8
1.12.228.33      26    5.8
59.2.248.106     26    5.8
47.243.137.229   26    5.8
24.188.199.170   26    5.8
8.210.37.176     26    5.8
43.100.119.45    25    5.6
172.232.232.169   9    2.0
172.236.137.159   9    2.0
172.232.232.179   6    1.3
172.232.232.10    6    1.3
114.70.38.81      5    1.1

In [22]:
## 6-2 ##
SCAN_CODES    = ["AH01092", "AH00126", "AH01276"]
BACKEND_CODES = ["AH00957", "AH01114", "AH01095", "AH01102", "AH00898"]
RESTART_CODES = ["AH01232", "AH02282", "AH02951", "AH00489", "AH00094", "AH00492"]

top_ips = ok["client_ip"].value_counts().head(10).index
ip_code = pd.crosstab(ok.loc[ok["client_ip"].isin(top_ips), "client_ip"],
                      ok.loc[ok["client_ip"].isin(top_ips), "error_code"])
display(ip_code)
scan_share = ok.loc[ok["client_ip"].isin(top_ips), "error_code"].isin(SCAN_CODES).mean() * 100
print(f"상위 10개 IP 요청 중 스캐닝 코드 비율: {scan_share:.1f}%")

# 백엔드 IP가 client로 찍힌 5건 확인
display(ok.loc[ok["client_ip"] == "114.70.38.81", ["timestamp", "error_code", "message"]])
ip_code.to_csv(OUT / "error_top_ip_by_code.csv", encoding="utf-8-sig")

error_code       AH00898  AH01092  AH01114  AH01276
client_ip
1.12.228.33            0       26        0        0
121.186.31.54          0       52        0        0
169.211.232.182        0       26        0        0
210.110.68.35          3        0       34        2
24.188.199.170         0       26        0        0
43.100.119.45          0       25        0        0
47.243.137.229         0       26        0        0
47.83.14.24            0       52        0        0
59.2.248.106           0       26        0        0
8.210.37.176           0       26        0        0

상위 10개 IP 요청 중 스캐닝 코드 비율: 88.6%

,timestamp,error_code,message
70,2025-06-16 15:38:15.389287,AH01114,AH01114: HTTP: failed to make connection to backend: 210.110.104.16
88,2025-06-16 15:49:51.029320,AH01114,AH01114: HTTP: failed to make connection to backend: 210.110.104.16
90,2025-06-16 15:50:51.160379,AH01114,"AH01114: HTTP: failed to make connection to backend: 210.110.104.16, referer: http://114.70.38.81/"
92,2025-06-16 15:52:58.166590,AH01114,AH01114: HTTP: failed to make connection to backend: 210.110.104.16
168,2025-06-16 17:21:22.331967,AH01114,AH01114: HTTP: failed to make connection to backend: 114.70.38.81

In [23]:
## 6-3 ##
a = ok.loc[ok["error_code"] == "AH00957", ["timestamp"]].sort_values("timestamp").rename(columns={"timestamp": "ts_957"})
b = ok.loc[ok["error_code"] == "AH01114", ["timestamp"]].sort_values("timestamp")
pair = pd.merge_asof(b, a, left_on="timestamp", right_on="ts_957",
                     direction="nearest", tolerance=pd.Timedelta("1s"))
n_pair = int(pair["ts_957"].notna().sum())
print(f"AH01114 {len(b)}건 중 1초 이내에 AH00957이 짝으로 있는 건: {n_pair}건")
print("최대 시간 차:", (pair["timestamp"] - pair["ts_957"]).abs().max())

AH01114 45건 중 1초 이내에 AH00957이 짝으로 있는 건: 45건
최대 시간 차: 0 days 00:00:00.000509

In [24]:
## 6-4 ##
has_client = ok["client_ip"].notna().map({True: "client 있음", False: "client 없음"})
code_client = pd.crosstab(ok["error_code"], has_client)
display(code_client)

mixed_client_codes = code_client[(code_client.get("client 있음", 0) > 0) &
                                 (code_client.get("client 없음", 0) > 0)].index.tolist()
e12_mask = ok["error_code"].isin(mixed_client_codes) & ok["client_ip"].isna()
print("client 유무가 섞인 코드:", mixed_client_codes)
print("그중 client 없는 행:", int(e12_mask.sum()))
code_client.to_csv(OUT / "error_code_by_client.csv", encoding="utf-8-sig")

client_ip   client 없음  client 있음
error_code
AH00094            18          0
AH00126             0          8
AH00489            18          0
AH00492            17          0
AH00898             0          3
AH00957            45          0
AH01092             0        387
AH01095             7          0
AH01102             3          0
AH01114             0         45
AH01232            18          0
AH01276             0          6
AH02282            18          0
AH02951            18          0

client 유무가 섞인 코드: []
그중 client 없는 행: 0

In [25]:
## 6-5 ##
all_days = pd.date_range(ts.min().normalize(), ts.max().normalize(), freq="D").date
missing_days = sorted(set(all_days) - set(ts.dt.date))
print(f"전체 {len(all_days)}일 중 로그 없는 날: {len(missing_days)}일")
print([str(d) for d in missing_days])

전체 46일 중 로그 없는 날: 10일
['2025-06-13', '2025-06-14', '2025-06-15', '2025-06-24', '2025-06-26', '2025-07-04', '2025-07-05', '2025-07-07', '2025-07-16', '2025-07-26']

In [27]:
## 7-2 / Error 품질 규칙 후보 ##

N = len(lines)
rules = [
    ("E01", "표준 헤더 없음(timestamp 누락)", len(no_ts),                                           "행", N, "형식 결함",   "데이터 품질", "VALID_ANOMALY 후보"),
    ("E02", "timestamp 변환 실패",           int(ok["timestamp"].isna().sum()),                     "행", N, "형식 결함",   "데이터 품질", "INVALID_DATA 후보"),
    ("E03", "허용값 외 level",               int(bad_level.sum()),                                  "행", N, "형식 결함",   "데이터 품질", "VALID_ANOMALY 후보"),
    ("E04", "module 누락",                   int(ok["module"].isna().sum()),                        "행", N, "형식 결함",   "데이터 품질", "INVALID_DATA 후보"),
    ("E05", "AH 코드 없음",                  int(ok["error_code"].isna().sum()),                    "행", N, "형식 결함",   "데이터 품질", "VALID_ANOMALY 후보"),
    ("E06", "같은 코드의 level 불일치",       int(ok["error_code"].isin(mixed_codes).sum()),         "행", N, "일관성",      "데이터 품질", "VALID_ANOMALY 후보"),
    ("E07", "client IP 형식 오류",           int((ok["client_ip_type"] == "INVALID").sum()),        "행", N, "형식 결함",   "데이터 품질", "INVALID_DATA 후보"),
    ("E08", "시간 역전",                     int((ok["timestamp"].diff() < pd.Timedelta(0)).sum()), "행", N, "일관성",      "데이터 품질", "VALID_ANOMALY 후보"),
    ("E09", "스캐닝·공격성 요청",             int(ok["error_code"].isin(SCAN_CODES).sum()),          "행", N, "보안 이벤트", "내용 이상",   "VALID_ANOMALY 후보"),
    ("E10", "동일 장애 중복 기록(AH00957+AH01114)", n_pair,                                          "쌍", len(b), "집계 주의", "내용 이상", "VALID (집계 시 중복 제거)"),
    ("E11", "서버 재시작 시퀀스 이벤트",       int(ok["error_code"].isin(RESTART_CODES).sum()),       "행", N, "운영 이벤트", "내용 이상",   "VALID (태그만)"),
    ("E12", "같은 코드인데 client 정보 누락",  int(e12_mask.sum()),                                   "행", N, "완전성",      "데이터 품질", "VALID_ANOMALY 후보"),
    ("E13", "로그가 없는 날짜",               len(missing_days),                                     "일", len(all_days), "적시성", "데이터 품질", "확인 필요 (Access와 대조)"),
]
rule_table = pd.DataFrame(rules, columns=["규칙 ID", "규칙", "위반 수", "단위", "분모", "이상 유형", "구분", "잠정 분류"])
rule_table["비율(%)"] = (rule_table["위반 수"] / rule_table["분모"] * 100).round(2)
display(rule_table)
rule_table.to_csv(OUT / "error_rule_candidates.csv", index=False, encoding="utf-8-sig")

,규칙 ID,규칙,위반 수,단위,분모,이상 유형,구분,잠정 분류,비율(%)
0,E01,표준 헤더 없음(timestamp 누락),18,행,629,형식 결함,데이터 품질,VALID_ANOMALY 후보,2.86
1,E02,timestamp 변환 실패,0,행,629,형식 결함,데이터 품질,INVALID_DATA 후보,0.00
2,E03,허용값 외 level,0,행,629,형식 결함,데이터 품질,VALID_ANOMALY 후보,0.00
3,E04,module 누락,0,행,629,형식 결함,데이터 품질,INVALID_DATA 후보,0.00
4,E05,AH 코드 없음,0,행,629,형식 결함,데이터 품질,VALID_ANOMALY 후보,0.00
5,E06,같은 코드의 level 불일치,0,행,629,일관성,데이터 품질,VALID_ANOMALY 후보,0.00
6,E07,client IP 형식 오류,0,행,629,형식 결함,데이터 품질,INVALID_DATA 후보,0.00
7,E08,시간 역전,0,행,629,일관성,데이터 품질,VALID_ANOMALY 후보,0.00
8,E09,스캐닝·공격성 요청,401,행,629,보안 이벤트,내용 이상,VALID_ANOMALY 후보,63.75
9,E10,동일 장애 중복 기록(AH00957+AH01114),45,쌍,45,집계 주의,내용 이상,VALID (집계 시 중복 제거),100.00
10,E11,서버 재시작 시퀀스 이벤트,107,행,629,운영 이벤트,내용 이상,VALID (태그만),17.01
11,E12,같은 코드인데 client 정보 누락,0,행,629,완전성,데이터 품질,VALID_ANOMALY 후보,0.00
12,E13,로그가 없는 날짜,10,일,46,적시성,데이터 품질,확인 필요 (Access와 대조),21.74

In [28]:
## 8-1 / 행마다 태그 달고 분류 ##

def row_tags(r):
    tags = []
    if r["error_code"] in SCAN_CODES:    tags.append("E09")
    if r["error_code"] in RESTART_CODES: tags.append("E11")
    if r["error_code"] in BACKEND_CODES: tags.append("BACKEND")
    if r["_e12"]:                        tags.append("E12")
    return ",".join(tags)

ok["_e12"] = e12_mask
ok["tags"] = ok.apply(row_tags, axis=1)

def classify(tags):
    t = set(tags.split(",")) if tags else set()
    return "VALID_ANOMALY" if t & {"E09", "E12"} else "VALID"
ok["quality_class"] = ok["tags"].map(classify)

def event_type(tags):
    if "E09" in tags: return "보안(스캐닝)"
    if "E11" in tags: return "운영(재시작)"
    if "BACKEND" in tags: return "운영(백엔드 장애)"
    return "기타"
ok["event_type"] = ok["tags"].map(event_type)

# 헤더 없는 18행도 포함해서 전체 629행 기준으로 합치기
hdr = pd.DataFrame({"line_no": no_ts["line_no"].values, "error_code": "AH00558",
                    "tags": "E01", "quality_class": "VALID_ANOMALY", "event_type": "운영(재시작)"})
row_class = pd.concat([ok.drop(columns="_e12"), hdr], ignore_index=True)

display(pd.crosstab(row_class["event_type"], row_class["quality_class"], margins=True, margins_name="합계"))
qc = row_class["quality_class"].value_counts().to_frame("건수")
qc["비율(%)"] = (qc["건수"] / len(row_class) * 100).round(1)
display(qc)

row_class.to_csv(OUT / "error_row_classification.csv", index=False, encoding="utf-8-sig")

quality_class  VALID  VALID_ANOMALY   합계
event_type
보안(스캐닝)            0            401  401
운영(백엔드 장애)       103              0  103
운영(재시작)          107             18  125
합계               210            419  629

                건수  비율(%)
quality_class
VALID_ANOMALY  419   66.6
VALID          210   33.4

In [29]:
## 8-2 / valid 정의표 ##

def ids(cond): return ", ".join(rule_table.loc[cond, "규칙 ID"])

valid_def = pd.DataFrame([
    ("VALID",
     "표준 헤더 존재, 필수 필드 추출 성공, 조사 대상 규칙 위반 없음. 재시작·백엔드 장애처럼 정상 기록된 운영 이벤트 포함(태그로 구분)",
     ids(rule_table["잠정 분류"].str.startswith("VALID (")),
     int((row_class["quality_class"] == "VALID").sum())),
    ("VALID_ANOMALY",
     "형식은 읽히거나 복구 가능하지만 조사가 필요한 데이터. 데이터 품질 이상(E01, E12)과 내용 이상(E09 스캐닝)으로 나뉨",
     ids(rule_table["잠정 분류"].str.startswith("VALID_ANOMALY")),
     int((row_class["quality_class"] == "VALID_ANOMALY").sum())),
    ("INVALID_DATA",
     "분석에 필요한 핵심 정보를 복구할 수 없는 데이터",
     ids(rule_table["잠정 분류"].str.startswith("INVALID")),
     int((row_class["quality_class"] == "INVALID_DATA").sum())),
], columns=["분류", "정의", "해당 규칙", "현재 건수"])
display(valid_def)
valid_def.to_csv(OUT / "error_valid_definition_draft.csv", index=False, encoding="utf-8-sig")

,분류,정의,해당 규칙,현재 건수
0,VALID,"표준 헤더 존재, 필수 필드 추출 성공, 조사 대상 규칙 위반 없음. 재시작·백엔드 장애처럼 정상 기록된 운영 이벤트 포함(태그로 구분)","E10, E11",210
1,VALID_ANOMALY,"형식은 읽히거나 복구 가능하지만 조사가 필요한 데이터. 데이터 품질 이상(E01, E12)과 내용 이상(E09 스캐닝)으로 나뉨","E01, E03, E05, E06, E08, E09, E12",419
2,INVALID_DATA,분석에 필요한 핵심 정보를 복구할 수 없는 데이터,"E02, E04, E07",0

In [30]:
## 품질 탐색 결과표 통합 ##

lv = ok["level"].value_counts()
scan_in_warn = ok.loc[ok["level"] == "warn", "error_code"].isin(SCAN_CODES).mean() * 100
by_date_top = ts.dt.date.value_counts().head(2)
restart_days = ok.loc[ok["error_code"] == "AH00489", "timestamp"].dt.date.value_counts().sort_index()

findings = pd.DataFrame([
    ("Error", "수집 기간",
     f"{ts.min():%Y-%m-%d %H:%M} ~ {ts.max():%Y-%m-%d %H:%M} ({(ts.max()-ts.min()).days}일)",
     f"{len(all_days)}일 중 {len(missing_days)}일 로그 없음 / " + ", ".join(f"{d} {n}건" for d, n in by_date_top.items()) + " 집중",
     "E08, E13"),
    ("Error", "헤더 없는 행", f"{len(no_ts)}건 (모두 AH00558)",
     "재시작 시퀀스 내 독립 메시지, 앞뒤 행으로 시각 복구 가능 / ServerName 미설정 반복", "E01"),
    ("Error", "Level 분포", ", ".join(f"{k} {v}" for k, v in lv.items()),
     f"warn의 {scan_in_warn:.0f}%가 스캐닝성 요청", "E03, E09"),
    ("Error", "Module 분포", ", ".join(f"{k} {v}" for k, v in ok["module"].value_counts().head(5).items()),
     f"재시작 관련 module 18건씩 → 재시작 {len(no_ts)}회 (" + ", ".join(f"{d} {n}회" for d, n in restart_days.items()) + ")",
     "E04, E11"),
    ("Error", "Error code", f"고유 {ok['error_code'].nunique()}개",
     f"스캐닝 {int(ok['error_code'].isin(SCAN_CODES).sum())}건 / 백엔드 장애 {int(ok['error_code'].isin(BACKEND_CODES).sum())}건(중복 쌍 {n_pair}) / 재시작 {int(ok['error_code'].isin(RESTART_CODES).sum())}건",
     "E05, E06, E09, E10, E11"),
    ("Error", "Client IP", f"고유 {ok['client_ip'].nunique()}개 / client 있는 행 {int(ok['client_ip'].notna().sum())}건",
     f"상위 10개 IP의 {scan_share:.0f}%가 스캐닝 코드 / 동일 건수 반복 IP 다수 / client 누락 {int(e12_mask.sum())}건",
     "E07, E12"),
], columns=["로그", "항목", "측정값", "발견 이슈", "관련 규칙"])
display(findings)
findings.to_csv(OUT / "error_quality_findings.csv", index=False, encoding="utf-8-sig")

,로그,항목,측정값,발견 이슈,관련 규칙
0,Error,수집 기간,2025-06-12 13:35 ~ 2025-07-27 22:36 (45일),"46일 중 10일 로그 없음 / 2025-06-16 149건, 2025-07-14 55건 집중","E08, E13"
1,Error,헤더 없는 행,18건 (모두 AH00558),"재시작 시퀀스 내 독립 메시지, 앞뒤 행으로 시각 복구 가능 / ServerName 미설정 반복",E01
2,Error,Level 분포,"warn 405, error 117, notice 89",warn의 96%가 스캐닝성 요청,"E03, E09"
3,Error,Module 분포,"proxy 442, proxy_http 48, mpm_event 35, core 26, http2 18","재시작 관련 module 18건씩 → 재시작 18회 (2025-06-12 6회, 2025-06-16 10회, 2025-07-06 2회)","E04, E11"
4,Error,Error code,고유 14개,스캐닝 401건 / 백엔드 장애 103건(중복 쌍 45) / 재시작 107건,"E05, E06, E09, E10, E11"
5,Error,Client IP,고유 74개 / client 있는 행 449건,상위 10개 IP의 89%가 스캐닝 코드 / 동일 건수 반복 IP 다수 / client 누락 0건,"E07, E12"